# Generated by Django 4.2.1 on 2023-06-08 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.service'),
        ),
    ]
