# Generated by Django 4.2.1 on 2023-06-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_alter_booking_sp_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
