# Generated by Django 4.2.1 on 2023-06-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_alter_serviceprovider_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.TextField(default='Kannur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='district',
            field=models.TextField(default='Kannur'),
            preserve_default=False,
        ),
    ]
